export const moviesCard = [
    {
        id: 1,
        image: '/movibox_Card/card-img1.png',
        date: 'USA, 2016 - Current',
        title: 'Stranger Things',
        rating: '86.0',
        percent: '97',
        category: 'Action, Adventure, Horror',
    },
    {
        id: 2,
        image: '/movibox_Card/card-img2.png',
        date: 'USA, 2005',
        title: 'Batman Begins',
        rating: '82.0',
        percent: '70',
        category: 'Action, Adventure',
    },
    {
        id: 3,
        image: '/movibox_Card/card-img3.png',
        date: 'USA, 2018',
        title: 'Spider-Man : Into The Spider Verse',
        rating: '84.0',
        percent: '87',
        category: 'Animation, Action, Adventure',
    },
    {
        id: 4,
        image: '/movibox_Card/card-img4.png',
        date: 'USA, 2017',
        title: 'Dunkirk',
        rating: '78.0',
        percent: '94',
        category: 'Action, Drama, History',
    },
    {
        id: 5,
        image: '/movibox_Card/card-img4.png',
        date: 'USA, 2017',
        title: 'Dunkirk',
        rating: '78.0',
        percent: '94',
        category: 'Action, Drama, History',
    },
]