export const moviesCard = [
    {
        id: 1,
        image: '/movibox_Card/card-img1.png',
        date: 'USA, 2016 - Current',
        title: 'Stranger Things',
        rating: '86.0',
        percent: '97',
        category: 'Action, Adventure, Horror',
        tvSeries: true,
    },
    {
        id: 2,
        image: '/movibox_Card/card-img2.png',
        date: 'USA, 2005',
        title: 'Batman Begins',
        rating: '82.0',
        percent: '70',
        category: 'Action, Adventure',
        tvSeries: false,
    },
    {
        id: 3,
        image: '/movibox_Card/card-img3.png',
        date: 'USA, 2018',
        title: 'Spider-Man : Into The Spider Verse',
        rating: '84.0',
        percent: '87',
        category: 'Animation, Action, Adventure',
        tvSeries: false,
    },
    {
        id: 4,
        image: '/movibox_Card/card-img4.png',
        date: 'USA, 2017',
        title: 'Dunkirk',
        rating: '78.0',
        percent: '94',
        category: 'Action, Drama, History',
        tvSeries: false,
    },
    {
        id: 5,
        image: '/movibox_Card/card-img5.png',
        date: 'USA, 2021',
        title: 'Dune',
        rating: '84.0',
        percent: '75',
        category: 'Action, Adventure, Drama',
        tvSeries: false,
    },
    {
        id: 6,
        image: '/movibox_Card/card-img6.png',
        date: 'USA, 2021',
        title: 'No Time To Die',
        rating: '76.0',
        percent: '68',
        category: 'Action, Adventure, Thriller',
        tvSeries: false,
    },
    {
        id: 7,
        image: '/movibox_Card/card-img7.png',
        date: 'USA, 2021',
        title: 'Shang-Chi and the Legend of the Ten Rings',
        rating: '79.0',
        percent: '71',
        category: 'Action, Adventure, Fantasy',
        tvSeries: false,
    },
    {
        id: 8,
        image: '/movibox_Card/card-img8.png',
        date: 'USA, 2021',
        title: 'Don\'t Breathe 2',
        rating: '61.0',
        percent: '46',
        category: 'Action, Drama, Horror ',
        tvSeries: false,
    },
]

export const newMoviesCard = [
    {
        id: 1,
        image: '/movibox_Card/card-img5.png',
        date: 'USA, 2021',
        title: 'Dune',
        rating: '84.0',
        percent: '75',
        category: 'Action, Adventure, Drama',
        tvSeries: false,
    },
    {
        id: 2,
        image: '/movibox_Card/card-img6.png',
        date: 'USA, 2021',
        title: 'No Time To Die',
        rating: '76.0',
        percent: '68',
        category: 'Action, Adventure, Thriller',
        tvSeries: false,
    },
    {
        id: 3,
        image: '/movibox_Card/card-img7.png',
        date: 'USA, 2021',
        title: 'Shang-Chi and the Legend of the Ten Rings',
        rating: '79.0',
        percent: '71',
        category: 'Action, Adventure, Fantasy',
        tvSeries: false,
    },
    {
        id: 4,
        image: '/movibox_Card/card-img8.png',
        date: 'USA, 2021',
        title: 'Don\'t Breathe 2',
        rating: '61.0',
        percent: '46',
        category: 'Action, Drama, Horror ',
        tvSeries: false,
    },
]